spring.application.name=smartparking
# ======= Spring DATASOURCE CONFIG ========
spring.datasource.url=jdbc:mysql://localhost:3306/smartparkingsystem
spring.datasource.username=root
spring.datasource.password=Ahem@9912

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# ======= Thymeleaf ========
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

# ======= Security login ========
spring.security.user.name=admin
spring.security.user.password=admin
server.port=8090